# Remove "..5.u.S"
TARGET="..5.u.S"
TARGET1="/sdcard/${TARGET}"
TARGET2="/sdcard/Android/data/${TARGET}"
TARGET3="/sdcard/Android/media/${TARGET}"
TARGET4="/sdcard/Android/obb/${TARGET}"
rm -rf "${TARGET1}"
rm -rf "${TARGET2}"
rm -rf "${TARGET3}"
rm -rf "${TARGET4}"
